[package]
name = "grundbegriffe"
version = "0.1"
lean_version = "leanprover-community/lean:3.24.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "66e02b35bc74304e21920b6dcf706d0118054244"}
